version: "3.9"


services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass12345
    volumes:
      -  ${PWD}/database:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb # MongoDB service (mongodb)
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true # Enable access to all databases as admin
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root # Admin username of the MongoDB database
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass12345 # Admin password of the MongoDB database 
      - ME_CONFIG_BASICAUTH_USERNAME=admin # Mongo-Express web interface access username
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123 # Mongo-Express web interface access password
    volumes:
      - mongodb-data
    depends_on:
      - mongo
    ports:
      - 8081:8081
    restart: unless-stopped
    links:
      - mongo

  health-service:
    image: health-service
    build:
      context: health-service/ # path specified under context 
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    volumes:
      - ${PWD}/health-service/:/usr/src/app
    links:
      - mongo
      

    




